version: "3"
services:
  whisper:
    build: ./whisper-container
    network_mode: host
    volumes:
      - ./shared:/shared

  llm:
    build: ./llm-container
    network_mode: host
    volumes:
      - ./shared:/shared

  llm-trt:
    build: ./llm-container-trt
    network_mode: host
    ports:
      - "11435:11434"  # Different port for TensorRT-LLM
    volumes:
      - ./shared:/shared

  tts:
    build: ./tts-container
    network_mode: host
    env_file: .env        # 👈 Add this line
    volumes:
      - ./shared:/shared
