"""
gui.complications.domains.financial -- Daily Brief overlay.

Sci-fi command-center HUD that surfaces the latest pending briefing
(generated by services.perpetual) along with dynamic visualisations
extracted from recent briefings:

  * Top arc:        "DAILY BRIEF" header + date / user
  * Headline band:  the first sentence of `insight` revealed with a
                    typewriter effect, ending in a blinking cursor
  * Center:         orbital "topic constellation" — the most-frequent
                    keywords across recent briefings rendered as nodes
                    on concentric orbits, linked by faint lines, sized
                    by frequency, slowly rotating
  * Around center:  four sci-fi gauges (SENTIMENT / URGENCY / NOVELTY
                    / CONFIDENCE) computed from the insight text
  * Bottom band:    ticker tape — supporting-evidence bullets scrolling
                    right-to-left
  * Background:     deep navy with a faint hexagonal grid and a vertical
                    scan line that passes every ~7 s

Class name + `name = "Financial"` are kept for registry compatibility
with the existing dock; only the `label` is renamed to "Daily Brief".
"""

from __future__ import annotations

import json
import math
import os
import re
import time
from pathlib import Path
from typing import TYPE_CHECKING, List, Tuple, Optional

if TYPE_CHECKING:
    from PyQt5.QtGui import QPainter

from PyQt5.QtCore import Qt, QPointF, QRectF
from PyQt5.QtGui import (
    QBrush, QColor, QFont, QLinearGradient, QPainterPath, QPen,
    QRadialGradient,
)

from gui.complications.domains.base_domain import BaseDomainComplication
from gui.renderer import clamp


# ─────────────────────────────────────────────────────────────────────────
# Data extraction
# ─────────────────────────────────────────────────────────────────────────

_BRIEFINGS_DIR = Path(__file__).resolve().parents[4] / "data" / "briefings"

_STOPWORDS = frozenset({
    # Articles / pronouns / prepositions
    "the", "a", "an", "and", "or", "but", "is", "are", "was", "were",
    "be", "been", "being", "have", "has", "had", "do", "does", "did",
    "will", "would", "could", "should", "may", "might", "shall", "can",
    "must", "of", "in", "on", "at", "to", "for", "with", "from", "by",
    "as", "into", "about", "after", "before", "up", "down", "out", "off",
    "over", "under", "again", "further", "then", "once", "here", "there",
    "when", "where", "why", "how", "all", "any", "both", "each", "few",
    "more", "most", "other", "some", "such", "no", "nor", "not", "only",
    "own", "same", "so", "than", "too", "very", "i", "me", "my", "myself",
    "we", "our", "ours", "ourselves", "you", "your", "yours", "he", "him",
    "his", "she", "her", "it", "its", "they", "them", "their", "theirs",
    "this", "that", "these", "those", "am", "im", "ill", "ive", "youre",
    "thats", "whats", "lets", "dont", "didnt", "wont", "wouldnt", "if",
    "yes", "no", "ok", "okay", "well", "right", "good", "morning", "today",
    "just", "also", "still", "really", "going", "got", "get", "got", "you",
    "us", "im", "let", "now", "one", "two", "lot", "way", "back",
    "around", "through", "things", "thing", "lot", "lots", "much", "make",
    "made", "see", "seen", "saying", "say", "said", "look", "looks",
    "looking", "seems", "seem", "seemed", "while",
})

# Lightweight sentiment cues — enough for a directional needle.
_POS_WORDS = frozenset({
    "great", "good", "excellent", "strong", "growth", "growing", "win",
    "wins", "wonderful", "excited", "exciting", "ready", "shipped",
    "shipping", "live", "active", "smooth", "seamless", "improved",
    "boost", "rally", "up", "rose", "gain", "gains", "gained", "success",
    "successful", "positive", "happy", "smart", "brilliant", "love",
    "promising", "bullish", "breakthrough", "milestone", "agreed",
    "approved", "deployed", "completed", "happy", "fast", "faster",
    "thriving", "robust", "healthy", "stable", "solid",
})
_NEG_WORDS = frozenset({
    "bad", "worse", "worst", "poor", "weak", "loss", "losses", "drop",
    "dropped", "crash", "crashed", "fail", "failed", "failure", "down",
    "fell", "fall", "falling", "decline", "concern", "concerned",
    "concerning", "risk", "risky", "issue", "problem", "stalled",
    "blocked", "blocker", "delay", "delayed", "outage", "broken", "bug",
    "regression", "negative", "alarming", "worried", "uncertain", "fear",
    "anxious", "danger", "threat", "threatened", "suffering", "stuck",
    "missing", "missed", "wrong",
})

_WORD_RE = re.compile(r"\b[a-zA-Z][a-zA-Z\-']{2,}\b")


def _read_briefing_json(path: Path) -> Optional[dict]:
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return None


def _load_recent_briefings(limit: int = 12) -> List[dict]:
    """Return up to *limit* most-recent JSON briefings."""
    if not _BRIEFINGS_DIR.is_dir():
        return []
    files = sorted(
        _BRIEFINGS_DIR.glob("*.json"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )[:limit]
    out = []
    for p in files:
        b = _read_briefing_json(p)
        if b:
            out.append(b)
    return out


def _extract_topics(text: str, top_n: int = 8) -> List[Tuple[str, int]]:
    """Most-frequent meaningful words in *text*."""
    counts: dict[str, int] = {}
    for w in _WORD_RE.findall(text or ""):
        wl = w.lower()
        if wl in _STOPWORDS or len(wl) < 4:
            continue
        counts[wl] = counts.get(wl, 0) + 1
    pairs = sorted(counts.items(), key=lambda kv: -kv[1])
    return pairs[:top_n]


def _sentiment_ratio(text: str) -> float:
    """Crude positive/negative split → 0..1 (0 = bleak, 1 = euphoric)."""
    pos = neg = 0
    for w in _WORD_RE.findall(text or ""):
        wl = w.lower()
        if wl in _POS_WORDS:
            pos += 1
        elif wl in _NEG_WORDS:
            neg += 1
    if pos + neg == 0:
        return 0.55  # default to a slight positive idle
    return clamp(pos / (pos + neg), 0.0, 1.0)


def _urgency_score(briefing: Optional[dict]) -> float:
    """Synthetic: knowledge gaps + supporting-evidence count + age."""
    if not briefing:
        return 0.30
    gaps = len(briefing.get("knowledge_gaps") or [])
    ev = len(briefing.get("supporting_evidence") or [])
    age_h = max(0.0, (time.time() - briefing.get("generated_at", time.time())) / 3600.0)
    # More gaps + more evidence → higher urgency, decays with age
    raw = (0.10 * ev) + (0.12 * gaps) + (0.30 / (1.0 + age_h * 0.3))
    return clamp(raw, 0.05, 1.0)


def _novelty_score(briefing: Optional[dict], topics: List[Tuple[str, int]]) -> float:
    """Rough proxy: more unique top topics → more novel."""
    if not topics:
        return 0.40
    # Diversity = count of unique topics with >=1 hit.
    unique = len([w for w, c in topics if c >= 1])
    return clamp(unique / 10.0 + 0.2, 0.0, 1.0)


def _first_sentence(text: str) -> str:
    """Pick a one-line headline — first sentence trimmed to ~110 chars."""
    if not text:
        return ""
    text = text.strip()
    # Split on first sentence terminator
    m = re.search(r"[.!?](\s|$)", text)
    if m:
        end = m.end()
        first = text[:end].strip()
    else:
        first = text
    if len(first) > 130:
        first = first[:127].rstrip() + "…"
    return first


# ─────────────────────────────────────────────────────────────────────────
# Visual constants — sci-fi HUD palette
# ─────────────────────────────────────────────────────────────────────────

# Cyan/teal command-center colors
_HUD_BG_DEEP   = QColor(4, 10, 22)
_HUD_BG_MID    = QColor(8, 18, 38)
_HUD_GRID      = QColor(60, 200, 230)        # alpha applied per draw
_HUD_PRIMARY   = QColor(120, 230, 255)
_HUD_ACCENT    = QColor(255, 195, 90)        # warm gold accent for guide stars
_HUD_DANGER    = QColor(255, 110, 105)
_HUD_OK        = QColor(110, 240, 175)
_HUD_TEXT      = QColor(220, 240, 255)
_HUD_TEXT_DIM  = QColor(140, 175, 210)


# ─────────────────────────────────────────────────────────────────────────
# Drawing helpers — modular pieces of the HUD
# ─────────────────────────────────────────────────────────────────────────

def _draw_hex_grid(p, cx, cy, R, t, alpha):
    """Faint hexagonal grid backdrop — drifts very slowly."""
    drift_x = (t * 4.0) % (R * 0.18)
    drift_y = (t * 1.5) % (R * 0.16)
    pen = QPen(QColor(_HUD_GRID.red(), _HUD_GRID.green(), _HUD_GRID.blue(), alpha))
    pen.setWidthF(max(0.35, R * 0.0018))
    p.setPen(pen)
    p.setBrush(Qt.NoBrush)
    side = R * 0.045
    h = side * math.sqrt(3.0) / 2.0
    rows = int((2 * R) / h) + 2
    cols = int((2 * R) / (1.5 * side)) + 2
    x0 = cx - R - drift_x
    y0 = cy - R - drift_y
    for r in range(rows):
        for c in range(cols):
            cxh = x0 + c * 1.5 * side
            cyh = y0 + r * 2 * h + (h if c % 2 else 0)
            # Skip if outside the dial
            if (cxh - cx) ** 2 + (cyh - cy) ** 2 > (R * 1.05) ** 2:
                continue
            path = QPainterPath()
            for k in range(6):
                ang = math.pi / 3.0 * k
                x = cxh + side * math.cos(ang)
                y = cyh + side * math.sin(ang)
                if k == 0:
                    path.moveTo(x, y)
                else:
                    path.lineTo(x, y)
            path.closeSubpath()
            p.drawPath(path)


def _draw_scan_line(p, cx, cy, R, t, trans):
    """Vertical scan line that passes top→bottom every ~7 s."""
    period = 7.0
    phase = (t % period) / period
    y = (cy - R) + phase * (2 * R)
    h_band = R * 0.16
    grad = QLinearGradient(0, y - h_band, 0, y + h_band)
    grad.setColorAt(0.0, QColor(0, 0, 0, 0))
    grad.setColorAt(0.5, QColor(_HUD_PRIMARY.red(), _HUD_PRIMARY.green(),
                                  _HUD_PRIMARY.blue(), int(60 * trans)))
    grad.setColorAt(1.0, QColor(0, 0, 0, 0))
    p.setPen(Qt.NoPen)
    p.setBrush(QBrush(grad))
    p.drawRect(QRectF(cx - R, y - h_band, 2 * R, 2 * h_band))


def _draw_arc_text(p, cx, cy, text, radius, center_deg, font, color,
                   spacing_deg=6.5, flip=False):
    chars = list(text)
    if flip:
        chars = chars[::-1]
    n = len(chars)
    if n == 0:
        return
    span = (n - 1) * spacing_deg
    start = center_deg - span * 0.5
    p.save()
    p.setFont(font)
    fm = p.fontMetrics()
    ch_h = fm.height()
    extra_rot = 180.0 if flip else 0.0
    for i, ch in enumerate(chars):
        a = math.radians(start + i * spacing_deg)
        x = cx + radius * math.cos(a)
        y = cy + radius * math.sin(a)
        ch_w = max(fm.horizontalAdvance(ch), ch_h)
        p.save()
        p.translate(x, y)
        p.rotate(math.degrees(a) + 90.0 + extra_rot)
        rect = QRectF(-ch_w * 0.7, -ch_h * 0.6, ch_w * 1.4, ch_h * 1.2)
        p.setPen(color)
        p.drawText(rect, Qt.AlignCenter, ch)
        p.restore()
    p.restore()


def _draw_gauge(p, cx, cy, radius, label, value, color, trans, t):
    """Sci-fi mini gauge — semicircular arc 210°→-30° with a needle.

    `value` is 0..1. `color` is the active arc color.
    """
    # Outer track
    track_pen = QPen(QColor(70, 110, 150, int(120 * trans)))
    track_pen.setWidthF(max(1.2, radius * 0.07))
    track_pen.setCapStyle(Qt.RoundCap)
    p.setPen(track_pen)
    p.setBrush(Qt.NoBrush)
    rect = QRectF(cx - radius, cy - radius, 2 * radius, 2 * radius)
    # Qt arc: degrees * 16
    p.drawArc(rect, int(210 * 16), int(-240 * 16))

    # Active arc (filled fraction of track)
    active_pen = QPen(color)
    active_pen.setWidthF(max(1.6, radius * 0.09))
    active_pen.setCapStyle(Qt.RoundCap)
    p.setPen(active_pen)
    sweep_deg = -240 * value
    p.drawArc(rect, int(210 * 16), int(sweep_deg * 16))

    # Tick marks on track
    tick_pen = QPen(QColor(140, 180, 220, int(110 * trans)))
    tick_pen.setWidthF(max(0.5, radius * 0.025))
    p.setPen(tick_pen)
    for k in range(11):
        ang = math.radians(210 - k * 24)
        r1 = radius - radius * 0.08
        r2 = radius - radius * 0.02
        x1 = cx + r1 * math.cos(ang)
        y1 = cy + r1 * math.sin(ang)
        x2 = cx + r2 * math.cos(ang)
        y2 = cy + r2 * math.sin(ang)
        p.drawLine(QPointF(x1, y1), QPointF(x2, y2))

    # Pulse halo on active arc tip
    tip_ang = math.radians(210 + sweep_deg)
    tip_x = cx + radius * math.cos(tip_ang)
    tip_y = cy + radius * math.sin(tip_ang)
    pulse = 0.6 + 0.4 * math.sin(t * 2.5)
    halo = QRadialGradient(QPointF(tip_x, tip_y), radius * 0.45)
    halo.setColorAt(0.0, QColor(color.red(), color.green(), color.blue(),
                                 int(160 * pulse * trans)))
    halo.setColorAt(1.0, QColor(0, 0, 0, 0))
    p.setPen(Qt.NoPen)
    p.setBrush(QBrush(halo))
    p.drawEllipse(QPointF(tip_x, tip_y), radius * 0.45, radius * 0.45)

    # Numeric readout
    num_font = QFont("Helvetica Neue", max(8, int(radius * 0.40)))
    num_font.setWeight(QFont.DemiBold)
    p.setFont(num_font)
    p.setPen(_HUD_TEXT)
    p.drawText(QRectF(cx - radius, cy - radius * 0.18, 2 * radius, radius * 0.45),
               Qt.AlignCenter, f"{int(value * 100):02d}")

    # Label below
    lbl_font = QFont("Helvetica Neue", max(6, int(radius * 0.18)))
    lbl_font.setLetterSpacing(QFont.PercentageSpacing, 145)
    lbl_font.setWeight(QFont.Medium)
    p.setFont(lbl_font)
    p.setPen(_HUD_TEXT_DIM)
    p.drawText(QRectF(cx - radius * 1.5, cy + radius * 0.30, 3 * radius, radius * 0.40),
               Qt.AlignCenter, label)


def _draw_constellation(p, cx, cy, R, topics, t, trans):
    """Topic constellation — keywords as glowing nodes orbiting the
    center, linked by faint lines."""
    if not topics:
        return
    n = min(len(topics), 8)
    # Two concentric orbits
    orbit_r1 = R * 0.30
    orbit_r2 = R * 0.46
    speed1 = 0.12
    speed2 = -0.08

    # Pre-compute positions
    positions = []
    weights = [c for _, c in topics[:n]]
    max_w = max(weights) if weights else 1
    for i, (word, count) in enumerate(topics[:n]):
        # Even indices on inner orbit, odd on outer
        if i % 2 == 0:
            r = orbit_r1
            ang = (i / max(1, (n + 1) // 2)) * 2 * math.pi + t * speed1
        else:
            r = orbit_r2
            ang = (i / max(1, n // 2)) * 2 * math.pi + t * speed2 + 0.4
        x = cx + r * math.cos(ang)
        y = cy + r * math.sin(ang)
        positions.append((x, y, word, count))

    # Connecting lines (each node to its 2 nearest neighbours)
    line_pen = QPen(QColor(_HUD_PRIMARY.red(), _HUD_PRIMARY.green(),
                            _HUD_PRIMARY.blue(), int(50 * trans)))
    line_pen.setWidthF(max(0.5, R * 0.0018))
    p.setPen(line_pen)
    p.setBrush(Qt.NoBrush)
    for i, (x1, y1, _, _) in enumerate(positions):
        # Distances to all others
        dists = []
        for j, (x2, y2, _, _) in enumerate(positions):
            if i == j:
                continue
            d = math.hypot(x2 - x1, y2 - y1)
            dists.append((d, j))
        dists.sort()
        for _, j in dists[:2]:
            x2, y2, _, _ = positions[j]
            p.drawLine(QPointF(x1, y1), QPointF(x2, y2))

    # Nodes + labels
    for i, (x, y, word, count) in enumerate(positions):
        # Node size by frequency
        sz = R * (0.018 + 0.030 * (count / max_w))
        # Halo
        halo = QRadialGradient(QPointF(x, y), sz * 4)
        halo.setColorAt(0.0, QColor(_HUD_PRIMARY.red(), _HUD_PRIMARY.green(),
                                     _HUD_PRIMARY.blue(), int(150 * trans)))
        halo.setColorAt(1.0, QColor(0, 0, 0, 0))
        p.setPen(Qt.NoPen)
        p.setBrush(QBrush(halo))
        p.drawEllipse(QPointF(x, y), sz * 4, sz * 4)
        # Body
        body = QRadialGradient(QPointF(x - sz * 0.3, y - sz * 0.3), sz * 1.4)
        body.setColorAt(0.0, QColor(255, 252, 240, int(245 * trans)))
        body.setColorAt(0.7, QColor(_HUD_PRIMARY.red(), _HUD_PRIMARY.green(),
                                     _HUD_PRIMARY.blue(), int(230 * trans)))
        body.setColorAt(1.0, QColor(40, 90, 130, int(190 * trans)))
        p.setBrush(QBrush(body))
        p.drawEllipse(QPointF(x, y), sz, sz)
        # Label (offset radially outward)
        ang = math.atan2(y - cy, x - cx)
        lx = x + math.cos(ang) * (sz + R * 0.04)
        ly = y + math.sin(ang) * (sz + R * 0.04)
        f = QFont("Helvetica Neue", max(7, int(R * 0.030)))
        f.setLetterSpacing(QFont.PercentageSpacing, 130)
        f.setWeight(QFont.Medium)
        p.setFont(f)
        p.setPen(QColor(_HUD_TEXT.red(), _HUD_TEXT.green(), _HUD_TEXT.blue(),
                         int(225 * trans)))
        rect = QRectF(lx - R * 0.15, ly - R * 0.04, R * 0.30, R * 0.08)
        p.drawText(rect, Qt.AlignCenter, word.upper())


def _draw_ticker_tape(p, cx, cy, R, items, t, trans):
    """Bottom band — supporting-evidence bullets scrolling right→left."""
    if not items:
        return
    band_y = cy + R * 0.78
    band_h = R * 0.10
    # Band background — subtle gradient
    grad = QLinearGradient(cx - R, 0, cx + R, 0)
    grad.setColorAt(0.0, QColor(0, 0, 0, 0))
    grad.setColorAt(0.10, QColor(_HUD_BG_DEEP.red(), _HUD_BG_DEEP.green(),
                                   _HUD_BG_DEEP.blue(), int(180 * trans)))
    grad.setColorAt(0.90, QColor(_HUD_BG_DEEP.red(), _HUD_BG_DEEP.green(),
                                   _HUD_BG_DEEP.blue(), int(180 * trans)))
    grad.setColorAt(1.0, QColor(0, 0, 0, 0))
    p.setPen(Qt.NoPen)
    p.setBrush(QBrush(grad))
    p.drawRect(QRectF(cx - R, band_y - band_h * 0.5, 2 * R, band_h))

    # Hairline edges
    edge_pen = QPen(QColor(_HUD_PRIMARY.red(), _HUD_PRIMARY.green(),
                            _HUD_PRIMARY.blue(), int(80 * trans)))
    edge_pen.setWidthF(max(0.5, R * 0.0014))
    p.setPen(edge_pen)
    p.drawLine(QPointF(cx - R * 0.85, band_y - band_h * 0.5),
               QPointF(cx + R * 0.85, band_y - band_h * 0.5))
    p.drawLine(QPointF(cx - R * 0.85, band_y + band_h * 0.5),
               QPointF(cx + R * 0.85, band_y + band_h * 0.5))

    # Compose ticker text
    sep = "   ◇   "
    ticker_text = sep.join(items) + sep
    f = QFont("Helvetica Neue", max(8, int(R * 0.035)))
    f.setWeight(QFont.Medium)
    f.setLetterSpacing(QFont.PercentageSpacing, 125)
    p.setFont(f)
    fm = p.fontMetrics()
    text_w = fm.horizontalAdvance(ticker_text)
    if text_w == 0:
        return
    # Scrolling offset
    scroll_speed = R * 0.18         # px / s
    offset = (t * scroll_speed) % text_w
    start_x = cx + R - offset
    p.setPen(QColor(_HUD_PRIMARY.red(), _HUD_PRIMARY.green(),
                     _HUD_PRIMARY.blue(), int(220 * trans)))
    # Draw two copies for seamless wrap
    p.drawText(QPointF(start_x, band_y + fm.descent() * 0.3), ticker_text)
    p.drawText(QPointF(start_x - text_w, band_y + fm.descent() * 0.3), ticker_text)


# ─────────────────────────────────────────────────────────────────────────
# Complication
# ─────────────────────────────────────────────────────────────────────────

class FinancialComplication(BaseDomainComplication):
    name = "Financial"        # registry compatibility with existing dock
    label = "Daily Brief"     # visible label — was "Financial"
    category = "Topics"

    def __init__(self, bus):
        super().__init__(bus)
        self._t0: float = 0.0
        # Cached extracted data
        self._cache_ts: float = 0.0
        self._headline: str = ""
        self._topics: List[Tuple[str, int]] = []
        self._evidence: List[str] = []
        self._sentiment: float = 0.55
        self._urgency: float = 0.30
        self._novelty: float = 0.40
        self._confidence: float = 0.50
        self._date_label: str = ""
        self._user_label: str = ""
        # Audio playback handle (for the briefing's pre-synthesised audio)
        self._audio_proc = None

    # ── Lifecycle hooks expected by the overlay routing ───────────────

    def play_audio(self):
        """If the pending briefing has a pre-synth WAV, play it."""
        from core.state import state
        b = state.pending_briefing
        if not b:
            return
        wav = b.get("audio_path")
        if not wav or not os.path.exists(wav):
            return
        try:
            from core.config import ALSA_PLAYBACK_DEVICE
            import subprocess
            self._audio_proc = subprocess.Popen(
                ["aplay", "-D", ALSA_PLAYBACK_DEVICE, "-q", wav],
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            )
        except Exception:
            self._audio_proc = None

    def stop_audio(self):
        if self._audio_proc and self._audio_proc.poll() is None:
            try:
                self._audio_proc.terminate()
            except Exception:
                pass
        self._audio_proc = None

    def draw_content(self, p, inner, t, accent):
        # The dock-tile glyph is drawn by BaseDomainComplication.
        pass

    # ── Cache refresh ─────────────────────────────────────────────────

    def _refresh(self) -> None:
        """Re-extract the headline / topics / gauges from current data.
        Cheap (~ a few ms even with a dozen briefings) but cached every
        20 s so the overlay doesn't re-parse on every frame."""
        from core.state import state

        recent = _load_recent_briefings(limit=12)
        pending = state.pending_briefing
        # Prefer the pending briefing for the headline + supporting bullets,
        # but pull topic frequency from the pending + history.
        primary = pending if pending else (recent[0] if recent else None)

        if primary:
            self._headline = _first_sentence(primary.get("insight") or "")
            self._evidence = list(primary.get("supporting_evidence") or [])
            self._confidence = clamp(float(primary.get("confidence") or 0.5),
                                     0.0, 1.0)
            ts = primary.get("generated_at")
            if ts:
                t_struct = time.localtime(ts)
                self._date_label = time.strftime("%b %d  %H:%M", t_struct).upper()
            else:
                self._date_label = primary.get("date", "").upper()
            self._user_label = (primary.get("user_name") or "").upper()
        else:
            self._headline = "STAND BY — NO BRIEF AVAILABLE"
            self._evidence = ["Awaiting next rumination cycle.",
                              "Tap to refresh."]
            self._confidence = 0.0
            self._date_label = time.strftime("%b %d  %H:%M").upper()
            self._user_label = ""

        # Topic frequency across history + pending
        all_text_parts = []
        if pending:
            all_text_parts.append(pending.get("insight") or "")
            for ev in pending.get("supporting_evidence") or []:
                all_text_parts.append(ev)
        for r in recent:
            all_text_parts.append(r.get("insight") or "")
        all_text = " ".join(all_text_parts)
        self._topics = _extract_topics(all_text, top_n=8)
        self._sentiment = _sentiment_ratio(all_text)
        self._urgency  = _urgency_score(primary)
        self._novelty  = _novelty_score(primary, self._topics)
        self._cache_ts = time.time()

    # ── Main overlay draw ─────────────────────────────────────────────

    def draw_overlay(self, p, cx, cy, mind, t, trans):
        a = clamp(float(trans), 0.0, 1.0)
        if a < 0.002:
            return
        if self._t0 == 0.0:
            self._t0 = t
        elapsed = max(0.0, t - self._t0)

        # Refresh cache occasionally
        if (time.time() - self._cache_ts) > 20.0 or not self._cache_ts:
            self._refresh()

        R = mind * 0.36

        p.save()
        try:
            p.setRenderHint(p.Antialiasing, True)

            # ── Clip to circle ───────────────────────────────────
            clip = QPainterPath()
            clip.addEllipse(QPointF(cx, cy), R, R)
            p.setClipPath(clip)

            # ── Deep navy backdrop with vignette ─────────────────
            bg = QRadialGradient(QPointF(cx, cy), R)
            bg.setColorAt(0.0, _HUD_BG_MID)
            bg.setColorAt(0.7, _HUD_BG_DEEP)
            bg.setColorAt(1.0, QColor(1, 3, 8))
            p.setPen(Qt.NoPen)
            p.setBrush(QBrush(bg))
            p.drawEllipse(QPointF(cx, cy), R, R)

            # Hex grid
            _draw_hex_grid(p, cx, cy, R, t, int(28 * a))

            # Scan line band
            _draw_scan_line(p, cx, cy, R, t, a)

            # ── Bezel — thin cyan ring ───────────────────────────
            bz_pen = QPen(QColor(_HUD_PRIMARY.red(), _HUD_PRIMARY.green(),
                                  _HUD_PRIMARY.blue(), int(160 * a)))
            bz_pen.setWidthF(max(1.6, mind * 0.0028))
            p.setPen(bz_pen)
            p.setBrush(Qt.NoBrush)
            p.drawEllipse(QPointF(cx, cy), R * 0.985, R * 0.985)
            inner_pen = QPen(QColor(_HUD_PRIMARY.red(), _HUD_PRIMARY.green(),
                                     _HUD_PRIMARY.blue(), int(70 * a)))
            inner_pen.setWidthF(max(1.0, mind * 0.0014))
            p.setPen(inner_pen)
            p.drawEllipse(QPointF(cx, cy), R * 0.94, R * 0.94)

            # ── Top arc: "DAILY BRIEF" ───────────────────────────
            hdr_font = QFont("Helvetica Neue", max(10, int(mind * 0.018)))
            hdr_font.setWeight(QFont.DemiBold)
            hdr_font.setLetterSpacing(QFont.PercentageSpacing, 175)
            _draw_arc_text(p, cx, cy, "DAILY  BRIEF", R * 0.86, -90.0,
                           hdr_font,
                           QColor(_HUD_PRIMARY.red(), _HUD_PRIMARY.green(),
                                   _HUD_PRIMARY.blue(), int(245 * a)),
                           spacing_deg=6.5)

            # ── Sub-arc: date / user ─────────────────────────────
            sub_font = QFont("Helvetica Neue", max(7, int(mind * 0.011)))
            sub_font.setWeight(QFont.Medium)
            sub_font.setLetterSpacing(QFont.PercentageSpacing, 165)
            sub_text = self._date_label
            if self._user_label:
                sub_text = f"{self._date_label}  ·  {self._user_label}"
            _draw_arc_text(p, cx, cy, sub_text, R * 0.78, -90.0,
                           sub_font,
                           QColor(_HUD_TEXT_DIM.red(), _HUD_TEXT_DIM.green(),
                                   _HUD_TEXT_DIM.blue(), int(220 * a)),
                           spacing_deg=5.0)

            # ── Headline (typewriter) ────────────────────────────
            h_text = self._headline
            # Reveal one character every 35 ms; hold 5 s when complete.
            chars_per_sec = 28.0
            typed = max(0, min(len(h_text), int(elapsed * chars_per_sec)))
            visible = h_text[:typed]
            cursor_on = (int(elapsed * 2.0) % 2 == 0)
            display = visible + ("▮" if cursor_on else " ")
            head_font = QFont("Helvetica Neue", max(9, int(mind * 0.0145)))
            head_font.setWeight(QFont.Medium)
            head_font.setLetterSpacing(QFont.PercentageSpacing, 115)
            p.setFont(head_font)
            p.setPen(QColor(_HUD_TEXT.red(), _HUD_TEXT.green(),
                             _HUD_TEXT.blue(), int(245 * a)))
            head_rect = QRectF(cx - R * 0.86, cy - R * 0.65,
                                R * 1.72, R * 0.18)
            p.drawText(head_rect, Qt.TextWordWrap | Qt.AlignHCenter | Qt.AlignTop,
                       display)

            # ── Center: topic constellation ──────────────────────
            _draw_constellation(p, cx, cy, R, self._topics, t, a)

            # ── Four sci-fi gauges around the constellation ──────
            gauge_radius = R * 0.085
            gauge_offset = R * 0.62
            # Top-left, top-right, bottom-left, bottom-right
            gauge_positions = [
                (cx - gauge_offset, cy - R * 0.20, "SENTIMENT", self._sentiment, _HUD_OK),
                (cx + gauge_offset, cy - R * 0.20, "URGENCY",   self._urgency,
                 _HUD_DANGER if self._urgency > 0.7 else _HUD_PRIMARY),
                (cx - gauge_offset, cy + R * 0.30, "NOVELTY",   self._novelty, _HUD_PRIMARY),
                (cx + gauge_offset, cy + R * 0.30, "CONFIDENCE", self._confidence,
                 _HUD_OK if self._confidence > 0.6 else _HUD_PRIMARY),
            ]
            for gx, gy, lbl, val, col in gauge_positions:
                _draw_gauge(p, gx, gy, gauge_radius, lbl, val,
                            QColor(col.red(), col.green(), col.blue(),
                                    int(255 * a)),
                            a, t)

            # ── Ticker tape (supporting evidence) ────────────────
            _draw_ticker_tape(p, cx, cy, R, self._evidence, t, a)

            # ── Bottom arc — call-to-action ──────────────────────
            cta_font = QFont("Helvetica Neue", max(7, int(mind * 0.011)))
            cta_font.setWeight(QFont.Medium)
            cta_font.setLetterSpacing(QFont.PercentageSpacing, 175)
            cta_alpha = int(180 * a)
            _draw_arc_text(p, cx, cy, "TAP  TO  HEAR  FULL  BRIEF",
                           R * 0.92, 90.0, cta_font,
                           QColor(_HUD_PRIMARY.red(), _HUD_PRIMARY.green(),
                                   _HUD_PRIMARY.blue(), cta_alpha),
                           spacing_deg=4.5, flip=True)

            # ── Decorative corner crosshairs (HUD touch) ─────────
            ch_pen = QPen(QColor(_HUD_PRIMARY.red(), _HUD_PRIMARY.green(),
                                  _HUD_PRIMARY.blue(), int(120 * a)))
            ch_pen.setWidthF(max(1.0, mind * 0.0018))
            p.setPen(ch_pen)
            arm = R * 0.05
            for sign_x in (-1, 1):
                for sign_y in (-1, 1):
                    base_x = cx + sign_x * R * 0.74
                    base_y = cy + sign_y * R * 0.46
                    p.drawLine(QPointF(base_x - arm, base_y),
                               QPointF(base_x + arm, base_y))
                    p.drawLine(QPointF(base_x, base_y - arm),
                               QPointF(base_x, base_y + arm))
        finally:
            p.restore()
