#!/bin/bash
#
# Set default audio output device to UACDemoV1.0 (USB Audio)
#
# This script configures ALSA and PulseAudio (if available) to use
# the UACDemoV1.0 USB audio device as the default output.
#
# Usage:
#   bash setup/scripts/set_default_audio.sh
#   Or: sudo bash setup/scripts/set_default_audio.sh
#

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_step() {
    echo ""
    echo -e "${BLUE}==========================================${NC}"
    echo -e "${BLUE}[STEP] $1${NC}"
    echo -e "${BLUE}==========================================${NC}"
}

# Get current user
AURA_USER="${SUDO_USER:-$USER}"
AURA_HOME="${HOME:-$(eval echo ~$AURA_USER)}"

print_step "Setting UACDemoV1.0 as default audio output"

# Check if device exists
print_info "Checking for UACDemoV1.0 device..."
if ! aplay -l 2>/dev/null | grep -q "UACDemoV1.0"; then
    print_error "UACDemoV1.0 device not found!"
    print_info "Available devices:"
    aplay -l 2>/dev/null || echo "  (aplay not available)"
    exit 1
fi

# Find card number
CARD_NUM=$(aplay -l 2>/dev/null | grep "UACDemoV1.0" | sed -n 's/.*card \([0-9]*\):.*/\1/p' | head -1)

if [ -z "$CARD_NUM" ]; then
    print_error "Could not determine card number for UACDemoV1.0"
    exit 1
fi

print_info "Found UACDemoV1.0 at card $CARD_NUM"

# ============================================================================
# Configure ALSA (~/.asoundrc)
# ============================================================================
print_step "Configuring ALSA default device"

ASOUNDRC="$AURA_HOME/.asoundrc"
ASOUNDRC_BACKUP="$AURA_HOME/.asoundrc.backup.$(date +%Y%m%d_%H%M%S)"

# Backup existing .asoundrc if it exists
if [ -f "$ASOUNDRC" ]; then
    print_info "Backing up existing .asoundrc to $ASOUNDRC_BACKUP"
    cp "$ASOUNDRC" "$ASOUNDRC_BACKUP"
fi

# Create/update .asoundrc
cat > "$ASOUNDRC" << EOF
# Default audio device: UACDemoV1.0 USB Audio
# Auto-generated by set_default_audio.sh

pcm.!default {
    type hw
    card $CARD_NUM
    device 0
}

ctl.!default {
    type hw
    card $CARD_NUM
}
EOF

chown "$AURA_USER:$AURA_USER" "$ASOUNDRC" 2>/dev/null || true
print_info "✅ ALSA default device set to card $CARD_NUM (UACDemoV1.0)"

# ============================================================================
# Configure PulseAudio (if available)
# ============================================================================
print_step "Configuring PulseAudio default device (if available)"

if command -v pactl >/dev/null 2>&1; then
    print_info "PulseAudio detected - configuring default sink..."
    
    # Find PulseAudio sink name for this device
    SINK_NAME=$(pactl list short sinks 2>/dev/null | grep -i "UACDemo\|card$CARD_NUM" | cut -f2 | head -1)
    
    if [ -n "$SINK_NAME" ]; then
        print_info "Found PulseAudio sink: $SINK_NAME"
        
        # Set as default sink
        if sudo -u "$AURA_USER" pactl set-default-sink "$SINK_NAME" 2>/dev/null; then
            print_info "✅ PulseAudio default sink set to: $SINK_NAME"
        else
            print_warning "Could not set PulseAudio default sink (may need to run without sudo)"
            print_info "   Try running: pactl set-default-sink \"$SINK_NAME\""
        fi
    else
        print_warning "Could not find PulseAudio sink for UACDemoV1.0"
        print_info "   Available sinks:"
        pactl list short sinks 2>/dev/null | sed 's/^/     /' || true
        print_info "   You can set it manually: pactl set-default-sink <sink_name>"
    fi
else
    print_info "PulseAudio not detected (using ALSA only)"
fi

# ============================================================================
# Test the configuration
# ============================================================================
print_step "Testing audio configuration"

print_info "Testing ALSA output..."
if echo "test" | aplay -q 2>/dev/null; then
    print_info "✅ ALSA test successful (card $CARD_NUM)"
else
    print_warning "ALSA test failed (this may be normal - no audio was actually played)"
fi

print_info "Current ALSA defaults:"
print_info "  PCM default: card $CARD_NUM (UACDemoV1.0)"
if command -v aplay >/dev/null 2>&1; then
    print_info "  Test with: echo 'test' | aplay -q"
fi

# ============================================================================
# Summary
# ============================================================================
echo ""
print_step "Configuration Complete"
echo ""
echo "✅ ALSA default device: card $CARD_NUM (UACDemoV1.0)"
if [ -f "$ASOUNDRC" ]; then
    echo "   Config file: $ASOUNDRC"
fi
if [ -f "$ASOUNDRC_BACKUP" ]; then
    echo "   Backup saved: $ASOUNDRC_BACKUP"
fi
echo ""
echo "💡 Note: You may need to:"
echo "   - Restart audio applications for changes to take effect"
echo "   - Or restart the system"
echo "   - Test with: echo 'test' | aplay -q"
echo ""

