services:
  whisper:
    build: ../whisper-container
    network_mode: host
    volumes:
      - ../shared:/shared

  llm-medical:
    build: ../llm-medical-container
    network_mode: host
    volumes:
      - ../shared:/shared
      - ../data:/app/data
      - /home/aura/LedgerAI/.env:/app/.env
    working_dir: /app
    env_file: /home/aura/LedgerAI/.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - medical

  llm-generic:
    build: ../llm-container
    network_mode: host
    volumes:
      - ../shared:/shared
      - ../data:/app/data
      - /home/aura/LedgerAI/.env:/app/.env
    working_dir: /app
    env_file: /home/aura/LedgerAI/.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - generic

