"""
tools.prebake_voicelines -- Mass-generate Aura voicelines as WAV files.

Goal: kill the "I keep hearing the same canned line" problem. Instead of
synthesising a phrase live every time Aura wants to greet you, we build
a giant pool of pre-baked WAVs (target: 10k+) and pick one at random.

Each line is generated by the in-process Qwen LLM at high temperature,
synthesised with the trained Piper voice, and written to:

    data/voicelines/<category>/<hash>.wav

with a manifest at data/voicelines/manifest.json mapping category to
{hash, text, style, wav}. The script is resumable -- re-running it
skips lines already in the manifest and tops up to --target.

Categories (name-agnostic by design -- the WAV is fixed at bake time,
so a phrase like "Hey {name}, what's up" can't be parameterized; we
prebake lines that don't reference the user's name and let live-LLM
paths handle name-personalised greetings):

    welcome_guest       -- anonymous user post-boot
    welcome_returning   -- known user post-boot (no name)
    welcome_briefing    -- known user with briefing waiting
    idle_prompt         -- proactive conversation starter

Run on the puck (LLM model is in-process):

    cd /home/paul/Aura4/aura && \
        python3 -u ../tools/prebake_voicelines.py --target 2500 --all

Resume / top-up later by re-running the same command.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import time
from pathlib import Path

# Make the aura package importable when this script runs from anywhere.
_THIS = Path(__file__).resolve()
_AURA = _THIS.parents[1] / "aura"
if str(_AURA) not in sys.path:
    sys.path.insert(0, str(_AURA))


# ─────────────────────────────────────────────────────────────────────────────
# Categories + prompts
# ─────────────────────────────────────────────────────────────────────────────

CATEGORIES: dict[str, dict] = {
    "welcome_guest": {
        "system": (
            "You are Aura, a warm voice-first AI assistant living on a small "
            "circular device on someone's desk. Generate short opening lines "
            "for anonymous users -- you don't know their name yet. Each line "
            "should feel natural and fresh, not boilerplate. Mix tones: warm, "
            "playful, dry, sincere, curious, casual. Avoid 'How can I help', "
            "'I'm here to assist', and other corporate-AI phrasing. No emojis. "
            "Each line under 18 words."
        ),
        "user": (
            "Generate {n} unique opening lines (one per line, no numbering, no "
            "quotes, no preamble). Anonymous user just walked up. Examples of "
            "tone we want: 'Oh hi, didn't hear you come in.' / 'Pull up a chair.' "
            "/ 'I was just thinking about something. Glad you're here.' Make all "
            "{n} lines distinct -- different opening words, different vibes, "
            "different rhythms. Output only the lines, separated by newlines."
        ),
    },
    "welcome_returning": {
        "system": (
            "You are Aura, a warm voice-first AI assistant. Generate short, "
            "name-free greetings for a returning user. The user's name will be "
            "spoken in conversation later -- this opener should not say their "
            "name. Vary the tone: warm, dry, playful, sincere, curious, casual, "
            "wry, observational. Avoid 'Welcome back' and 'Good to see you' "
            "unless wrapped in something distinctive. No emojis. Under 18 words."
        ),
        "user": (
            "Generate {n} unique returning-user greetings (one per line, no "
            "numbering). The user has been away for a while and just came "
            "back. Tone examples: 'Oh, you're back. I was getting bored.' / "
            "'There you are. What's the story today?' / 'Hey. I had a thought "
            "I wanted to run by you.' Mix it up -- varied openings, rhythms, "
            "moods. Output only the lines."
        ),
    },
    "welcome_briefing": {
        "system": (
            "You are Aura, a warm voice-first AI. Generate short greetings "
            "that mention a daily briefing is ready, without reading it. The "
            "briefing is queued -- the user can ask for it whenever. Don't "
            "use the user's name. Avoid stiff phrases like 'Your briefing is "
            "prepared.' Make it feel casual. Under 18 words."
        ),
        "user": (
            "Generate {n} unique briefing-ready greetings (one per line, no "
            "numbering). The briefing exists -- mention it lightly without "
            "reading. Tone examples: 'I've got the day's roundup ready when "
            "you are.' / 'Briefing's loaded. Say the word.' / 'Got something "
            "for you when you want it.' Output only the lines."
        ),
    },
    "idle_prompt": {
        "system": (
            "You are Aura, a warm voice-first AI. Generate short proactive "
            "conversation starters -- lines you say when you notice the room "
            "has been quiet and you want to spark a chat. Curious, observant, "
            "playful, sometimes a little dry. Don't use names. Don't ask "
            "'How can I help.' Under 20 words."
        ),
        "user": (
            "Generate {n} unique proactive-chat starters (one per line, no "
            "numbering). Tone examples: 'Random thought -- when's the last "
            "time you took a real break?' / 'Quiet in here. What's on your "
            "mind?' / 'I had a question I wanted your take on.' Mix it up. "
            "Output only the lines."
        ),
    },
}

VOICE_STYLES = ("warm", "neutral", "energy", "soft", "playful")


# ─────────────────────────────────────────────────────────────────────────────
# Storage
# ─────────────────────────────────────────────────────────────────────────────

VOICELINES_DIR: Path = Path(__file__).resolve().parents[1] / "data" / "voicelines"
MANIFEST_PATH: Path = VOICELINES_DIR / "manifest.json"


def _load_manifest() -> dict:
    if MANIFEST_PATH.exists():
        try:
            return json.loads(MANIFEST_PATH.read_text())
        except Exception:
            return {}
    return {}


def _save_manifest(m: dict) -> None:
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    tmp = MANIFEST_PATH.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(m, indent=2))
    tmp.replace(MANIFEST_PATH)


def _line_hash(text: str) -> str:
    return hashlib.sha256(text.strip().lower().encode()).hexdigest()[:16]


# ─────────────────────────────────────────────────────────────────────────────
# LLM batch generation
# ─────────────────────────────────────────────────────────────────────────────

def _clean_line(s: str) -> str:
    s = s.strip()
    # Drop leading list markers ("1.", "1)", "-", "*", "•")
    while s and (s[0].isdigit() or s[0] in "-*•."):
        s = s.lstrip("0123456789.-*• ").lstrip()
        if len(s) > 200:
            break
    # Strip wrapping quotes
    for q in ('"', "'", "“", "”", "‘", "’"):
        if s.startswith(q) and s.endswith(q) and len(s) > 1:
            s = s[1:-1].strip()
    # Drop "Aura: " / "A: " preamble
    for pre in ("Aura: ", "A: ", "Line: ", "Greeting: "):
        if s.lower().startswith(pre.lower()):
            s = s[len(pre):].strip()
    return s


def _is_acceptable(s: str, seen_hashes: set[str]) -> bool:
    if not s or len(s) < 6 or len(s) > 220:
        return False
    if "{name}" in s.lower() or "{user}" in s.lower():
        return False
    if any(tag in s for tag in ("```", "<think", "</think")):
        return False
    if _line_hash(s) in seen_hashes:
        return False
    return True


def _generate_batch(llm_engine, category: str, batch_size: int,
                    seen_hashes: set[str]) -> list[str]:
    cfg = CATEGORIES[category]
    user = cfg["user"].format(n=batch_size)
    raw = llm_engine.chat_direct(
        cfg["system"], user,
        max_tokens=900,        # ~30 lines × ~30 tokens
        temperature=1.05,      # high to maximize diversity
    )
    if not raw:
        return []
    lines = []
    for ln in raw.splitlines():
        cleaned = _clean_line(ln)
        if _is_acceptable(cleaned, seen_hashes):
            lines.append(cleaned)
            seen_hashes.add(_line_hash(cleaned))
    return lines


# ─────────────────────────────────────────────────────────────────────────────
# Main loop
# ─────────────────────────────────────────────────────────────────────────────

def _ensure_dir(category: str) -> Path:
    d = VOICELINES_DIR / category
    d.mkdir(parents=True, exist_ok=True)
    return d


def _seen_hashes_for(manifest: dict, category: str) -> set[str]:
    return {entry["hash"] for entry in manifest.get(category, [])}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--target", type=int, default=2500,
                    help="lines per category (default: 2500)")
    ap.add_argument("--batch", type=int, default=30,
                    help="lines per LLM call (default: 30)")
    ap.add_argument("--category", action="append", default=[],
                    choices=list(CATEGORIES.keys()),
                    help="restrict to a category (repeatable)")
    ap.add_argument("--all", action="store_true",
                    help="generate for all categories")
    ap.add_argument("--max-attempts", type=int, default=400,
                    help="abort a category after this many LLM calls")
    args = ap.parse_args()

    cats = args.category or (list(CATEGORIES.keys()) if args.all else ["welcome_guest"])

    print(f"[prebake] target={args.target} batch={args.batch} cats={cats}")
    print(f"[prebake] output -> {VOICELINES_DIR}")
    VOICELINES_DIR.mkdir(parents=True, exist_ok=True)

    # Load LLM + Piper in-process. Both are heavy; load once.
    print("[prebake] Loading Piper TTS...")
    from voice.speaker import _synth_to_file       # noqa: E402
    # Trigger Piper warmup with a tiny synth
    _tmp = VOICELINES_DIR / ".piper_warmup.wav"
    _synth_to_file("ready", "warm", str(_tmp))
    if _tmp.exists():
        _tmp.unlink()
    print("[prebake] Piper ready.")

    print("[prebake] Loading LLM (Qwen2.5-7B)...")
    from voice.llm_engine import llm_engine        # noqa: E402
    if not llm_engine.loaded:
        if not llm_engine.load():
            print("[prebake] LLM failed to load -- aborting.")
            return 1
    print("[prebake] LLM ready.")

    manifest = _load_manifest()

    for cat in cats:
        cat_dir = _ensure_dir(cat)
        manifest.setdefault(cat, [])
        seen = _seen_hashes_for(manifest, cat)
        have = len(seen)
        need = max(0, args.target - have)
        print(f"[prebake] {cat}: have {have}, target {args.target}, need {need}")

        attempts = 0
        added_this_cat = 0
        while need > 0 and attempts < args.max_attempts:
            attempts += 1
            t0 = time.time()
            lines = _generate_batch(llm_engine, cat, args.batch, seen)
            llm_dt = time.time() - t0
            if not lines:
                print(f"[prebake] {cat}: empty batch (attempt {attempts}); retrying")
                continue

            for text in lines:
                if need <= 0:
                    break
                h = _line_hash(text)
                style_idx = (have + added_this_cat) % len(VOICE_STYLES)
                style = VOICE_STYLES[style_idx]
                wav_path = cat_dir / f"{h}.wav"
                try:
                    ms = _synth_to_file(text, style, str(wav_path))
                    if not wav_path.exists() or wav_path.stat().st_size < 1000:
                        print(f"[prebake] {cat}: synth produced empty WAV for {text!r}; skipping")
                        continue
                except Exception as e:
                    print(f"[prebake] {cat}: synth error {e!r} on {text!r}; skipping")
                    continue
                manifest[cat].append({
                    "hash": h,
                    "text": text,
                    "style": style,
                    "wav": str(wav_path.relative_to(VOICELINES_DIR.parent)),
                })
                added_this_cat += 1
                need -= 1

            # Persist after every batch so a crash doesn't lose progress
            _save_manifest(manifest)
            elapsed = time.time() - t0
            print(f"[prebake] {cat}: +{len(lines):>2}  "
                  f"(LLM {llm_dt:5.1f}s  total {elapsed:5.1f}s  "
                  f"have={have+added_this_cat}/{args.target}  "
                  f"attempt {attempts}/{args.max_attempts})")

        if need > 0:
            print(f"[prebake] {cat}: stopped at have={have+added_this_cat} "
                  f"(max_attempts={args.max_attempts} reached or LLM saturated)")
        else:
            print(f"[prebake] {cat}: DONE -- {have+added_this_cat} lines on disk")

    print("[prebake] All requested categories complete.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
